---
title: SPEL
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Space and Planetary Exploration Laboratory
baseurl: ''
mail: mailto:spel@ing.uchile.cl
github: http://github.com/proyectosuchai
permalink: none
future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
paginate_path: blog/page:num
paginate: 10
