title: 'SPEL'
subtitle: 'Space and Planetary Exploration Laboratory'

baseurl: ''

# Social
mail: mailto:spel@ing.uchile.cl
github: http://github.com/proyectosuchai
#facebook:
#twitter: http://twitter.com/spel

# Dates are not included in permalinks
permalink: none

# Since these are pages, it doesn't really matter
future: true

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
    
# Paginator
paginate_path: 'blog/page:num'
paginate: 10
