source 'https://rubygems.org'

require 'json'
require 'open-uri'
require 'jekyll-paginate'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']